<?php

use Illuminate\Database\Seeder;
use App\Fonction;

class FonctionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $fonctions = ["COORDONNATEUR NATIONAL", "RESPONSABLE TECHNIQUE", "COORDONNATEUR DE POLE", "COORDONNATEUR DEPARTEMENTAL",
        "TECHNICIEN DE SURFACE", "RESPONSABLE FINANCIER", "RESPONSABLE ADMINISTRATIF", "RESPONSABLE SUIVI EVALUATION",
        "CHEF DE ZONE", "CHEF DE SECTEUR", "OPERATEUR", "CHAUDRONNIER", "SURVEILLANT DE DEPOT", "CONTROLEUR", "SECRETAIRE",
        "CHEF SERVICE D'EXPLOITATION", "AMBASSADRICE", "CHAUFFEUR", "CHEF DE DEPARTEMENT", "GARDIEN", "SUPERVISEUR",
        "CHEF DE SECTEUR", "INSPECTEUR", "EMPLOYE", "ASSISTANT RH", "ASSISTANT TECHNIQUE", "ASSISTANTE ADMINISTRATIVE",
         "COORDONNATEUR", "CHEF DE  SECTEUR", "COURSIER", "ASSISTANT ADMINISTRATIF", "AGENT DE SAISIE",
         "ADMINISTRATIF FINANCIER COMPTABLE", "GUIDEUR", "ASSISTANTE DE DIRECTION", "GERANT MUTUELLE", "ENTRETIEN LOCAUX",
         "COMPTABLE IPM", "INGENIEUR EN INFORMATIQUE", "INGENIEUR TELECOM&RESEAUX", "CHEF DE PROJET", "RESPONSABLE SIG",
         "COORDONNATEUR CELLULE"];

        foreach ($fonctions as $fonction) {
            Fonction::create(
              [
                'libelle' => $fonction
              ]
            );
        }
    }
}
